update `oc_country` SET `name`= 'Україна' WHERE `name`= 'Ukraine';
update `oc_zone` SET `name`= 'Черкаська' WHERE `name` LIKE '%Cherkas%';
update `oc_zone` SET `name`= 'Чернігівська' WHERE `name` LIKE '%Chernihivs%';
update `oc_zone` SET `name`= 'Чернівецька' WHERE `name` LIKE '%Chernivets%';
update `oc_zone` SET `name`= 'Крим' WHERE `name` LIKE '%Crimea%';
update `oc_zone` SET `name`= 'Дніпропетровська' WHERE `name` LIKE '%Dnipropetrovs%';
update `oc_zone` SET `name`= 'Донецька' WHERE `name` LIKE '%Donets%';
update `oc_zone` SET `name`= 'Івано-Франківська' WHERE `name` LIKE '%Ivano-Frankivs%';
update `oc_zone` SET `name`= 'Херсонська' WHERE `name` LIKE '%Khersons%';
update `oc_zone` SET `name`= 'Хмельницька' WHERE `name` LIKE '%Khmel%';
update `oc_zone` SET `name`= 'Кіровоградська' WHERE `name` LIKE '%Kirovohrads%';
update `oc_zone` SET `name`= 'Київ' WHERE `name` = 'Kyiv';
update `oc_zone` SET `name`= 'Київська' WHERE `name` LIKE '%Kyivs%';
update `oc_zone` SET `name`= 'Луганська' WHERE `name` LIKE '%Luhans%';
update `oc_zone` SET `name`= 'Львівська' WHERE `name` LIKE '%vivs%';
update `oc_zone` SET `name`= 'Миколаївська' WHERE `name` LIKE '%Mykolayivs%';
update `oc_zone` SET `name`= 'Одеська' WHERE `name` LIKE '%Odes%';
update `oc_zone` SET `name`= 'Полтавська' WHERE `name` LIKE '%Poltavs%';
update `oc_zone` SET `name`= 'Рівненська' WHERE `name` LIKE '%Rivnens%';
update `oc_zone` SET `name`= 'Севастополь' WHERE `name` LIKE '%Sevastopol%';
update `oc_zone` SET `name`= 'Сумська' WHERE `name` LIKE '%Sums%';
update `oc_zone` SET `name`= 'Тернопільська' WHERE `name` LIKE '%Ternopil%';
update `oc_zone` SET `name`= 'Вінницька' WHERE `name` LIKE '%Vinnyts%';
update `oc_zone` SET `name`= 'Волинська' WHERE `name` LIKE '%Volyns%';
update `oc_zone` SET `name`= 'Закарпатська' WHERE `name` LIKE '%Zakarpats%';
update `oc_zone` SET `name`= 'Запорізька' WHERE `name` LIKE '%Zaporiz%';
update `oc_zone` SET `name`= 'Житомирська' WHERE `name` LIKE '%Zhytomyrs%';
update `oc_zone` SET `name`= 'Харківська' WHERE `name` LIKE '%Kharkivs%'; 
update `oc_information_description` SET `title`= 'Про нас',`description`='&lt;p&gt;Про нас&lt;/p&gt;',`meta_title`='Про нас' WHERE (`title`='About Us') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));  
update `oc_information_description` SET `title`= 'Політика конфіденційності',`description`='&lt;p&gt;Політика конфіденційності&lt;/p&gt;',`meta_title`='Політика конфіденційності' WHERE (`title`='Privacy Policy') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));  
update `oc_information_description` SET `title`= 'Доставка',`description`='&lt;p&gt;Доставка&lt;/p&gt;',`meta_title`='Доставка' WHERE (`title`='Delivery Information') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));  
update `oc_information_description` SET `title`= 'Правила та умови',`description`='&lt;p&gt;Правила та умови&lt;/p&gt;',`meta_title`='Правила та умови' WHERE (`title`='Terms &amp; Conditions') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));  
update `oc_information_description` SET `title`= 'О нас',`description`='&lt;p&gt;О насs&lt;/p&gt;',`meta_title`='О нас' WHERE (`title`='About Us') AND `language_id`= 3;  
update `oc_information_description` SET `title`= 'Политика конфиденциальности',`description`='&lt;p&gt;Политика конфиденциальности&lt;/p&gt;',`meta_title`='Политика конфиденциальности' WHERE (`title`='Privacy Policy') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));  
update `oc_information_description` SET `title`= 'Доставка',`description`='&lt;p&gt;Доставка&lt;/p&gt;',`meta_title`='Доставка' WHERE (`title`='Delivery Information') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));  
update `oc_information_description` SET `title`= 'Правила и условия',`description`='&lt;p&gt;Правила и условия&lt;/p&gt;',`meta_title`='Правила и условия' WHERE (`title`='Terms &amp; Conditions') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));  
UPDATE `oc_order_status` SET `name`='В обробці' WHERE (`name` = 'Processing') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Відправлений' WHERE (`name` = 'Shipped') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Скасований' WHERE (`name` = 'Canceled') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Виконаний' WHERE (`name` = 'Complete') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Заборонений' WHERE (`name` = 'Denied') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Знятий з резерву' WHERE (`name` = 'Canceled Reversal') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Помилковий' WHERE (`name` = 'Failed') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Повернений' WHERE (`name` = 'Refunded') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Зарезервовано' WHERE (`name` = 'Reversed') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Повернення коштів' WHERE (`name` = 'Chargeback') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='В очікуванні' WHERE (`name` = 'Pending') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Скасовано' WHERE (`name` = 'Voided ') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Опрацьований' WHERE (`name` = 'Processed') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Закінчився термін' WHERE (`name` = 'Expired') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_order_status` SET `name`='Обрабатывается' WHERE (`name` = 'Processing') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='Отправлен' WHERE (`name` = 'Shipped') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='Отменён' WHERE (`name` = 'Canceled') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='Исполнен' WHERE (`name` = 'Complete') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='Запрещён' WHERE (`name` = 'Denied') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='Снят с резерва' WHERE (`name` = 'Canceled Reversal') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='Ошибочный' WHERE (`name` = 'Failed') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='Возвращён' WHERE (`name` = 'Refunded') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='Зарезервирован' WHERE (`name` = 'Reversed') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='Возврат денег' WHERE (`name` = 'Chargeback') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='В ожидании' WHERE (`name` = 'Pending') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='Отменён' WHERE (`name` = 'Voided ') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='Отработан' WHERE (`name` = 'Processed') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_order_status` SET `name`='Заканчивается срок' WHERE (`name` = 'Expired') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_stock_status` SET `name`='В наявності' WHERE (`name` = 'In Stock') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_stock_status` SET `name`='Під замовлення' WHERE (`name` = 'Pre-Order') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_stock_status` SET `name`='Немає на складі' WHERE (`name` = 'Out Of Stock') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_stock_status` SET `name`='Під замов. 2-3 дні' WHERE (`name` = '2-3 Days') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_stock_status` SET `name`='В наличии' WHERE (`name` = 'In Stock') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_stock_status` SET `name`='Под заказ' WHERE (`name` = 'Pre-Order') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_stock_status` SET `name`='Нет на складе' WHERE (`name` = 'Out Of Stock') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_stock_status` SET `name`='Под заказ 2-3 дня' WHERE (`name` = '2-3 Days') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_return_action` SET `name`='Повернений' WHERE (`name` = 'Refunded') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_return_action` SET `name`='Повернено кошти' WHERE (`name` = 'Credit Issued') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_return_action` SET `name`='Відправлено заміну' WHERE (`name` = 'Replacement Sent') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_return_action` SET `name`='Возвращённый' WHERE (`name` = 'Refunded') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_return_action` SET `name`='Возвращены деньги' WHERE (`name` = 'Credit Issued') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_return_action` SET `name`='Отрпавлена замена' WHERE (`name` = 'Replacement Sent') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_return_status` SET `name`='Не оброблений' WHERE (`name` = 'Pending') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_return_status` SET `name`='Виконаний' WHERE (`name` = 'Complete') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_return_status` SET `name`='Чекаємо товар від клієнта' WHERE (`name` = 'Awaiting Products') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_return_status` SET `name`='Не обработан' WHERE (`name` = 'Pending') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_return_status` SET `name`='Исполнен' WHERE (`name` = 'Complete') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_return_status` SET `name`='Ждём товар от клиента' WHERE (`name` = 'Awaiting Products') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_length_class_description` SET `title`='Сантиметр' WHERE (`title` = 'Centimeter') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_length_class_description` SET `unit`='см' WHERE (`unit` = 'cm') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_length_class_description` SET `title`='Міліметр' WHERE (`title` = 'Millimeter') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_length_class_description` SET `unit`='мм' WHERE (`unit` = 'mm') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_length_class_description` SET `title`='Дюйм' WHERE (`title` = 'Inch') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_length_class_description` SET `title`='Сантиметр' WHERE (`title` = 'Centimeter') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_length_class_description` SET `unit`='см' WHERE (`unit` = 'cm') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_length_class_description` SET `title`='Милиметр' WHERE (`title` = 'Millimeter') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_length_class_description` SET `unit`='мм' WHERE (`unit` = 'mm') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_length_class_description` SET `title`='Дюйм' WHERE (`title` = 'Inch') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_weight_class_description` SET `title`='Кілограм' WHERE (`title` = 'Kilogram') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_length_class_description` SET `unit`='кг' WHERE (`unit` = 'kg') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_weight_class_description` SET `title`='Грам' WHERE (`title` = 'Gram') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_length_class_description` SET `unit`='г' WHERE (`unit` = 'g') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_weight_class_description` SET `title`='Фунт' WHERE (`title` = 'Pound') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_length_class_description` SET `unit`='фунтів' WHERE (`unit` = 'lb') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_weight_class_description` SET `title`='Унція' WHERE (`title` = 'Ounce') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_length_class_description` SET `unit`='унцій' WHERE (`unit` = 'oz') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_weight_class_description` SET `title`='Килограмм' WHERE (`title` = 'Kilogram') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_length_class_description` SET `unit`='кг' WHERE (`unit` = 'kg') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_weight_class_description` SET `title`='Грам' WHERE (`title` = 'Gram') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_length_class_description` SET `unit`='г' WHERE (`unit` = 'g') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_weight_class_description` SET `title`='Фунт' WHERE (`title` = 'Pound') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_length_class_description` SET `unit`='фунтов' WHERE (`unit` = 'lb') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_weight_class_description` SET `title`='Унция' WHERE (`title` = 'Ounce') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_length_class_description` SET `unit`='унций' WHERE (`unit` = 'oz') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_return_reason` SET `name`='Товар пошкоджено' WHERE (`name` = 'Dead On Arrival') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_return_reason` SET `name`='Прибув інший товар' WHERE (`name` = 'Received Wrong Item') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_return_reason` SET `name`='Помилка замовлення' WHERE (`name` = 'Order Error') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_return_reason` SET `name`='Неправильні деталі замовлення' WHERE (`name` = 'Faulty, please supply details') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_return_reason` SET `name`='Інші, будь ласка, надайте деталі' WHERE (`name` = 'Other, please supply details') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'uk-ua'));
UPDATE `oc_return_reason` SET `name`='Товар испорчен' WHERE (`name` = 'Dead On Arrival') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_return_reason` SET `name`='Пришол другой товар' WHERE (`name` = 'Received Wrong Item') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_return_reason` SET `name`='Ошибка заказа' WHERE (`name` = 'Order Error') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_return_reason` SET `name`='Неправильные детали заказа' WHERE (`name` = 'Faulty, please supply details') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));
UPDATE `oc_return_reason` SET `name`='Другое, пожалуйста, представте детали' WHERE (`name` = 'Other, please supply details') AND (`language_id` = (SELECT `language_id` FROM `oc_language` WHERE `code` = 'ru-ru'));